name: Run DSSP on uploaded PDB file

on:
  push:
    paths:
      - '**.pdb'
  workflow_dispatch:

jobs:
  dssp-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DSSP
        run: sudo apt-get update && sudo apt-get install -y dssp

      - name: Add HEADER line to PDB and run DSSP
        run: |
          echo 'HEADER    ALPHAFOLD MODEL                         01-JAN-00   SEED3' > fixed.pdb
          tail -n +2 seed3 >> fixed.pdb
          mkdssp fixed.pdb output.dssp


      - name: Upload DSSP output
        uses: actions/upload-artifact@v4
        with:
          name: dssp-output
          path: output.dssp
