name: Run DSSP on uploaded PDB file

on:
  push:
    paths:
      - '**.pdb'

jobs:
  dssp-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DSSP
        run: sudo apt-get update && sudo apt-get install -y dssp

      - name: Run DSSP
        run: mkdssp -i test_9db52_0_unrelaxed_rank_001_alphafold2_ptm_model_3_seed_000.pdb -o output.dssp

      - name: Upload DSSP output
        uses: actions/upload-artifact@v4
        with:
          name: dssp-output
          path: output.dssp
