name: Run DSSP on uploaded PDB file

on:
  push:
    paths:
      - '**.pdb'
  workflow_dispatch:

jobs:
  dssp-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DSSP
        run: sudo apt-get update && sudo apt-get install -y dssp

      - name: Run DSSP
        run: |
          which mkdssp
          mkdssp --version
          mkdssp seed3.pdb output.dssp

      - name: Upload DSSP output
        uses: actions/upload-artifact@v4
        with:
          name: dssp-output
          path: output.dssp
